https://ci.appveyor.com/project/spyder-ide/pywinpty/

matrix:
  fast_finish: true

environment:
  global:
    # Used by qthelpers to close widgets after a defined time
    TEST_CI: True
    CYTHON_COVERAGE: 1
    # Environment variables used by astropy helpers
    PYTHON: "C:\\conda"
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
    PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                      # of 32 bit and 64 bit builds are needed, move this
                      # to the matrix section.

  matrix:
    - PYTHON_VERSION: "3.6"
    - PYTHON_VERSION: "3.5"

platform:
  -x64

install:
  # Astropy ci-helpers. See https://github.com/astropy/ci-helpers
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  # Install the selected Qt version
  - "conda install --file requirements.txt -c spyder-ide"
  - "python setup.py develop"

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - ciocheck winpty --disable-tests
  - conda remove -n test pytest-xdist
  - pytest winppty
